"""empty message

Revision ID: d9c6b5a32c03
Revises: 3c96fe0fad95
Create Date: 2021-06-23 20:49:22.115129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c6b5a32c03'
down_revision = '3c96fe0fad95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'avatar')
    # ### end Alembic commands ###
